In [1]:
import pandas as pd
import os

In [2]:
print("Current working directory:", os.getcwd())

Current working directory: C:\Users\Harpreet\Desktop\EduPro_Project\notebooks

In [41]:
learner_profile = pd.read_csv("../outputs/clustered_learners.csv")
courses = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Courses.csv")
transactions = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Transactions.csv")

In [4]:
learner_profile

,UserID,UserName,Age,Gender,Email,total_courses,enrollment_frequency,avg_spending,total_spending,diversity_score,avg_course_rating,preferred_category,preferred_level,learning_depth_index,preferred_teacher,teacher_diversity,cluster
0,U00001,wilsonjordan,15,Male,patricia27@hotmail.com,1,1,394.260000,394.26,1,1.350000,Cybersecurity,Intermediate,0.0,TC00031,1,1
1,U00002,angela22,29,Female,hallrandy@hotmail.com,1,1,0.000000,0.00,1,2.880000,Programming,Beginner,0.0,TC00009,1,1
2,U00003,morrisonamanda,33,Female,ganderson@yahoo.com,11,11,55.816364,613.98,7,2.889091,Marketing,Advanced,0.8,TC00040,2,2
3,U00004,fthornton,23,Female,christensencatherine@outlook.com,13,13,75.542308,982.05,8,3.451538,Digital Marketing,Intermediate,0.6,TC00040,2,2
4,U00005,fostergeoffrey,21,Male,karenfuentes@yahoo.com,2,2,173.355000,346.71,2,2.055000,Programming,Advanced,0.5,TC00015,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,U02996,rebeccamccoy,32,Male,james28@outlook.com,1,1,0.000000,0.00,1,4.140000,Finance,Beginner,0.0,TC00048,1,1
2996,U02997,jburke,21,Female,nramos@yahoo.com,1,1,0.000000,0.00,1,1.810000,Machine Learning,Advanced,1.0,TC00017,1,1
2997,U02998,choikendra,33,Male,katherinebeck@hotmail.com,1,1,37.890000,37.89,1,1.300000,Web Development,Advanced,1.0,TC00034,1,1
2998,U02999,rachelmalone,20,Male,rodgerserica@hotmail.com,1,1,37.890000,37.89,1,1.300000,Web Development,Advanced,1.0,TC00026,1,1
2999,U03000,harperdouglas,15,Male,jackie41@gmail.com,1,1,394.260000,394.26,1,1.350000,Cybersecurity,Intermediate,0.0,TC00001,1,1

In [5]:
transactions

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,25/10/2025,0.00,PayPal,TC00040
1,TT00002,U00003,CR00037,13/1/2025,0.00,PayPal,TC00040
2,TT00003,U00003,CR00019,28/3/2025,0.00,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2/6/2025,0.00,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,10/8/2025,0.00,PayPal,TC00042
...,...,...,...,...,...,...,...
9995,TT09996,U02974,CR00045,1/12/2025,0.00,Credit Card,TC00040
9996,TT09997,U02976,CR00017,3/4/2025,0.00,PayPal,TC00040
9997,TT09998,U02980,CR00060,1/6/2025,0.00,PayPal,TC00040
9998,TT09999,U02981,CR00055,26/4/2025,57.32,Bank Transfer,TC00040
9999,TT10000,U02984,CR00043,18/10/2025,0.00,Credit Card,TC00042

In [6]:
courses

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28
5,CR00006,Graphic Design Basics,Design,Paid,Advanced,276.37,48.84,2.72
6,CR00007,UI/UX Design,Design,Free,Advanced,0.00,48.68,2.61
7,CR00008,Photoshop Mastery,Design,Free,Advanced,0.00,2.87,1.52
8,CR00009,Web Design Fundamentals,Design,Free,Beginner,0.00,48.19,4.51
9,CR00010,3D Modeling,Design,Free,Advanced,0.00,15.29,4.45
10,CR00011,Entrepreneurship 101,Business,Paid,Intermediate,326.02,11.31,2.69
11,CR00012,Business Strategy,Business,Paid,Advanced,487.92,36.01,3.64
12,CR00013,Finance for Startups,Business,Free,Advanced,0.00,15.84,2.00
13,CR00014,Sales Mastery,Business,Free,Advanced,0.00,22.29,3.15
14,CR00015,Leadership Essentials,Business,Paid,Beginner,285.05,34.78,1.96
15,CR00016,Digital Marketing,Marketing,Free,Intermediate,0.00,42.68,4.72
16,CR00017,SEO Mastery,Marketing,Free,Advanced,0.00,29.37,4.79
17,CR00018,Social Media Marketing,Marketing,Free,Advanced,0.00,15.44,2.01
18,CR00019,Content Marketing,Marketing,Free,Advanced,0.00,18.00,2.98
19,CR00020,Email Marketing,Marketing,Free,Intermediate,0.00,46.25,4.11
20,CR00021,Data Analysis with Python,Data Science,Free,Intermediate,0.00,1.20,3.60
21,CR00022,Data Visualization,Data Science,Free,Beginner,0.00,32.64,3.65
22,CR00023,Machine Learning Fundamentals,Data Science,Free,Intermediate,0.00,9.71,3.02
23,CR00024,Big Data Analytics,Data Science,Paid,Advanced,117.68,48.09,2.57
24,CR00025,Statistical Analysis,Data Science,Paid,Beginner,299.57,48.32,3.74
25,CR00026,Intro to Machine Learning,Machine Learning,Free,Intermediate,0.00,47.70,4.73
26,CR00027,Neural Networks,Machine Learning,Free,Advanced,0.00,9.30,1.81
27,CR00028,Deep Learning,Machine Learning,Paid,Advanced,0.78,44.96,3.89
28,CR00029,Natural Language Processing,Machine Learning,Free,Beginner,0.00,16.33,1.13
29,CR00030,Reinforcement Learning,Machine Learning,Free,Intermediate,0.00,38.49,1.73
30,CR00031,Network Security,Cybersecurity,Free,Intermediate,0.00,26.52,1.91
31,CR00032,Ethical Hacking,Cybersecurity,Free,Advanced,0.00,16.74,2.38
32,CR00033,Cybersecurity Fundamentals,Cybersecurity,Free,Intermediate,0.00,48.25,3.93
33,CR00034,Data Encryption,Cybersecurity,Paid,Intermediate,394.26,47.44,1.35
34,CR00035,Cyber Threat Intelligence,Cybersecurity,Free,Beginner,0.00,42.59,4.94
35,CR00036,Agile Project Management,Project Management,Free,Beginner,0.00,15.75,4.68
36,CR00037,Scrum Essentials,Project Management,Free,Intermediate,0.00,33.93,3.45
37,CR00038,Risk Management,Project Management,Paid,Intermediate,342.61,17.14,4.84
38,CR00039,Project Planning,Project Management,Paid,Advanced,346.71,3.42,1.23
39,CR00040,Leadership in Projects,Project Management,Paid,Beginner,327.99,12.13,1.51
40,CR00041,Financial Accounting,Finance,Paid,Beginner,53.86,47.08,2.47
41,CR00042,Investment Strategies,Finance,Free,Intermediate,0.00,34.83,4.10
42,CR00043,Corporate Finance,Finance,Free,Beginner,0.00,31.77,4.14
43,CR00044,Personal Finance,Finance,Paid,Intermediate,119.04,23.41,2.75
44,CR00045,Financial Modeling,Finance,Free,Advanced,0.00,6.36,1.59
45,CR00046,AI for Beginners,Artificial Intelligence,Paid,Beginner,248.10,9.40,1.20
46,CR00047,Natural Language Processing,Artificial Intelligence,Paid,Intermediate,89.59,1.55,2.68
47,CR00048,AI Ethics,Artificial Intelligence,Free,Beginner,0.00,42.70,3.64
48,CR00049,Deep Learning,Artificial Intelligence,Paid,Intermediate,415.51,28.33,3.11
49,CR00050,Computer Vision,Artificial Intelligence,Paid,Beginner,490.90,7.55,4.55
50,CR00051,HTML & CSS,Web Development,Paid,Advanced,37.89,24.11,1.30
51,CR00052,JavaScript Mastery,Web Development,Free,Beginner,0.00,40.76,2.20
52,CR00053,React for Beginners,Web Development,Free,Advanced,0.00,40.07,2.67
53,CR00054,Backend Development with Node.js,Web Development,Free,Beginner,0.00,48.57,3.32
54,CR00055,Full-Stack Web Development,Web Development,Paid,Advanced,57.32,43.95,4.74
55,CR00056,Google Ads Mastery,Digital Marketing,Paid,Advanced,212.39,22.89,3.15
56,CR00057,SEO for E-commerce,Digital Marketing,Paid,Advanced,177.34,49.73,3.89
57,CR00058,Social Media Strategy,Digital Marketing,Free,Beginner,0.00,1.46,4.44
58,CR00059,Affiliate Marketing,Digital Marketing,Free,Intermediate,0.00,5.95,4.66
59,CR00060,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14

### Merge for Recommendation Logic

In [7]:
data = transactions.merge(courses, on='CourseID', how='left')

In [8]:
data

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,TT00001,U00003,CR00016,25/10/2025,0.00,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.00,42.68,4.72
1,TT00002,U00003,CR00037,13/1/2025,0.00,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.00,33.93,3.45
2,TT00003,U00003,CR00019,28/3/2025,0.00,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.00,18.00,2.98
3,TT00004,U00004,CR00048,2/6/2025,0.00,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.00,42.70,3.64
4,TT00005,U00004,CR00060,10/8/2025,0.00,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TT09996,U02974,CR00045,1/12/2025,0.00,Credit Card,TC00040,Financial Modeling,Finance,Free,Advanced,0.00,6.36,1.59
9996,TT09997,U02976,CR00017,3/4/2025,0.00,PayPal,TC00040,SEO Mastery,Marketing,Free,Advanced,0.00,29.37,4.79
9997,TT09998,U02980,CR00060,1/6/2025,0.00,PayPal,TC00040,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14
9998,TT09999,U02981,CR00055,26/4/2025,57.32,Bank Transfer,TC00040,Full-Stack Web Development,Web Development,Paid,Advanced,57.32,43.95,4.74
9999,TT10000,U02984,CR00043,18/10/2025,0.00,Credit Card,TC00042,Corporate Finance,Finance,Free,Beginner,0.00,31.77,4.14

### Recommendation Function

In [22]:
def recommend_courses(user_id, top_n=5):
    
    # Step 1: Get user cluster
    user_cluster = learner_profile[
        learner_profile['UserID'] == user_id
    ]['cluster'].values[0]
    
    # Step 2: Get users in same cluster
    similar_users = learner_profile[
        learner_profile['cluster'] == user_cluster
    ]['UserID']
    
    # Step 3: Get their course enrollments
    cluster_data = data[data['UserID'].isin(similar_users)]
    
    # Step 4: Remove already enrolled courses
    user_courses = data[data['UserID'] == user_id]['CourseID']
    
    cluster_data = cluster_data[
        ~cluster_data['CourseID'].isin(user_courses)
    ]
    
    # Step 5: Score courses (Popularity + Rating)
    course_scores = cluster_data.groupby('CourseID').agg({
        'UserID': 'count',           # popularity
        'CourseRating': 'mean'       # quality
    }).rename(columns={
        'UserID': 'popularity',
        'CourseRating': 'avg_rating'
    })
    
    # Normalize scores
    course_scores['score'] = (
        course_scores['popularity'] * 0.6 +
        course_scores['avg_rating'] * 0.4
    )
    
    # Step 6: Top recommendations
    top_courses = course_scores.sort_values(
        by='score', ascending=False
    ).head(top_n)
    
    # Step 7: Return course details
    recommendations = courses[
        courses['CourseID'].isin(top_courses.index)
    ]
    
    return recommendations

In [24]:
user_cluster

array([1, 1, 1, 0, 0], dtype=int32)

### Test the System

In [35]:
def get_user_data(user_id):
    return learner_profile[learner_profile['UserID'] == user_id]

In [39]:
get_user_data("U00004")

,UserID,UserName,Age,Gender,Email,total_courses,enrollment_frequency,avg_spending,total_spending,diversity_score,avg_course_rating,preferred_category,preferred_level,learning_depth_index,preferred_teacher,teacher_diversity,cluster
3,U00004,fthornton,23,Female,christensencatherine@outlook.com,13,13,75.542308,982.05,8,3.451538,Digital Marketing,Intermediate,0.6,TC00040,2,2